services:
  api:
    container_name: minimarketApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    command: bash -c ' yarn migration:run && yarn dev'
    depends_on:
      - pg
  pg:
  container_name: minimarketDB
  image: postgres
  env_file:
    - .env
  expose:
    - 5432
  ports:
    - 5432:5432
