version: "3"

services:
  api:
    container_name: minimarketApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pg
  pg:
    container_name: minimarketDB
    image: postgres
    env_file:
      - .env
    expose:
      - ${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
